version: '3.9'
services:
  app:
    image: ${APP_IMAGE:?}
    depends_on:
      - mongo
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/.cache
    environment:
      ADDRESS: ${ADDRESS:?}
      ENABLE_TLS: ${ENABLE_TLS}
      TLS_ADDRESS: ${TLS_ADDRESS:?}
      AUTH_USER: ${AUTH_USER:?}
      AUTH_PASS: ${AUTH_PASS:?}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: ${MONGO_USER:?}
      MONGO_PASSWORD: ${MONGO_PASS:?}
      MONGO_DATABASE: ${MONGO_DATABASE:?}
      MONGO_COLLECTION: ${MONGO_COLLECTION:?}
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:?}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:?}
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_USER:?}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_PASS:?}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER:?}:${MONGO_PASS:?}@mongo:27017/
volumes:
  db-data:
  autocert_cache: