# this file is meant for Docker Swarm stacks only
# trying it in compose will fail because of multiple replicas trying to bind to the same port
# Swarm currently does not support Compose Spec, so we'll pin to the older version 3.9

version: '3.9'
services:
  app:
    build:
      dockerfile: .docker/app/Dockerfile
      context: .
      target: dev
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    networks:
      - my_net
    environment:
      ENV: ${AUTH_USER:?ENV is not set}
      AUTH_USER: ${AUTH_USER:?AUTH_USER is not set}
      AUTH_PASS: ${AUTH_PASS:?AUTH_PASS is not set}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: ${MONGO_USER:?MONGO_USER is not set}
      MONGO_PASSWORD: ${MONGO_PASS:?MONGO_PASS is not set}
      MONGO_DATABASE: ${MONGO_DATABASE:?MONGO_DATABASE is not set}
      MONGO_COLLECTION: ${MONGO_COLLECTION:?MONGO_COLLECTION is not set}
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:?MONGO_USER is not set}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:?MONGO_PASS is not set}
    networks:
      - my_net
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    networks:
      - my_net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER:?MONGO_USER is not set}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS:?MONGO_PASS is not set}
      ME_CONFIG_MONGODB_URL: "mongodb://${cgroup_vol}:${cgroup_vol}mongo:27017/"

networks:
  my_net:
    driver: bridge
volumes:
  db-data:

