version: '3.9'
services:
  app:
    image: ${APP_IMAGE}
    build:
      dockerfile: .docker/app/Dockerfile
      context: .
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    networks:
      - my_net
    volumes:
      - autocert_cache:/var/www/.cache
    environment:
      ENV: ${ENV:?ENV is missing}
      ADDRESS: ${ADDRESS:?ADDRESS is missing}
      AUTH_USER: ${AUTH_USER:?AUTH_USER is missing}
      AUTH_PASS: ${AUTH_PASS:?AUTH_PASS is missing}
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: ${MONGO_USER:?MONGO_USER is missing}
      MONGO_PASSWORD: ${MONGO_PASS:?MONGO_PASS is missing}
      MONGO_DATABASE: ${MONGO_DATABASE:?MONGO_DATABASE is missing}
      MONGO_COLLECTION: ${MONGO_COLLECTION:?MONGO_COLLECTION is missing}
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:?MONGO_USER is missing}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:?MONGO_PASS is missing}
    networks:
      - my_net
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    networks:
      - my_net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_USER:?MONGO_EXPRESS_USER is missing}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_PASS:?MONGO_EXPRESS_PASS is missing}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/

networks:
  my_net:
volumes:
  db-data:
  autocert_cache:

